
FIND_PATH (QEXTSERIALPORT_INCLUDE_DIR NAMES 
    qextserialport.h 
    qextserialportenumerator.h 
    qextserialport_global.h
)

FIND_LIBRARY(QEXTSERIALPORT_LIBRARY NAMES
    qextserialport
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(QextSerialPort DEFAULT_MSG QEXTSERIALPORT_LIBRARY QEXTSERIALPORT_INCLUDE_DIR)

IF(QEXTSERIALPORT_FOUND)
    SET(QEXTSERIALPORT_LIBRARIES ${QEXTSERIALPORT_LIBRARY})
    SET(QEXTSERIALPORT_INCLUDE_DIRS ${QEXTSERIALPORT_INCLUDE_DIR})
ENDIF(QEXTSERIALPORT_FOUND)
